import CoreImage
import UIKit
import Vision

/// Client-side image duties from §6.3: Gate 1 hand detection, downscale to a 1024px
/// long edge, and a clean JPEG re-encode that strips all EXIF (GPS, device, timestamps).
enum ImageProcessor {

    /// Gate 1 confidence threshold — generated by the calibration sweep, never edited
    /// by hand. See GateThresholds.swift for the value's provenance.
    static var gate1ConfidenceThreshold: Float { GateThresholds.gate1Confidence }

    /// Gate 1: on-device hand detection (§6.2). Non-hands never leave the phone.
    /// Detects hand *pose*, so backs of hands pass here — palm-vs-dorsum is Gate 3's job.
    static func detectHand(in image: UIImage) async throws -> Bool {
        guard let cgImage = image.cgImage else { return false }

        let request = VNDetectHumanHandPoseRequest()
        request.maximumHandCount = 2

        let orientation = CGImagePropertyOrientation(image.imageOrientation)
        let handler = VNImageRequestHandler(cgImage: cgImage, orientation: orientation)

        return try await Task.detached(priority: .userInitiated) {
            try handler.perform([request])
            let confidences = (request.results ?? []).map(\.confidence)
            return confidences.contains { $0 >= gate1ConfidenceThreshold }
        }.value
    }

    /// Centered crop to a target width:height ratio, matching the crop
    /// `AVCaptureVideoPreviewLayer`'s `.resizeAspectFill` applies when it displays the
    /// live feed inside a hole of a different aspect than the sensor: scale to cover,
    /// then keep only the centered region that was visible. Used so what Gate 1 judges
    /// and what gets uploaded is exactly what the user saw framed on screen — not extra
    /// sensor area the aspect-filled preview silently cropped away from view.
    ///
    /// Normalizes orientation first (draws through `UIImage.draw(in:)`, which honors
    /// `imageOrientation`) so the crop rect is computed and applied in the same upright,
    /// on-screen space the user aligned their hand in, regardless of how the camera
    /// reported the buffer's raw orientation.
    static func crop(_ image: UIImage, toAspect targetAspect: CGFloat) -> UIImage {
        let format = UIGraphicsImageRendererFormat()
        format.scale = image.scale
        let displaySize = image.size
        let normalized = UIGraphicsImageRenderer(size: displaySize, format: format).image { _ in
            image.draw(in: CGRect(origin: .zero, size: displaySize))
        }
        guard let cgImage = normalized.cgImage else { return image }

        let pixelWidth = CGFloat(cgImage.width)
        let pixelHeight = CGFloat(cgImage.height)
        let sourceAspect = pixelWidth / pixelHeight

        let cropRect: CGRect
        if sourceAspect > targetAspect {
            // Source is relatively wider than the hole — crop the sides, keep full height.
            let cropWidth = (pixelHeight * targetAspect).rounded()
            cropRect = CGRect(x: ((pixelWidth - cropWidth) / 2).rounded(), y: 0,
                               width: cropWidth, height: pixelHeight)
        } else {
            // Source is relatively taller than the hole — crop top/bottom, keep full width.
            let cropHeight = (pixelWidth / targetAspect).rounded()
            cropRect = CGRect(x: 0, y: ((pixelHeight - cropHeight) / 2).rounded(),
                               width: pixelWidth, height: cropHeight)
        }

        guard let cropped = cgImage.cropping(to: cropRect) else { return normalized }
        return UIImage(cgImage: cropped, scale: normalized.scale, orientation: .up)
    }

    /// Downscale to a 1024px long edge and re-encode as JPEG at 0.8 quality.
    /// Re-encoding through UIGraphicsImageRenderer produces a fresh bitmap with no
    /// source metadata, which is the EXIF strip §6.1 requires (GPS included).
    static func prepareForUpload(_ image: UIImage) -> Data? {
        let longEdge: CGFloat = 1024
        let size = image.size
        let scale = min(1, longEdge / max(size.width, size.height))
        let target = CGSize(width: (size.width * scale).rounded(), height: (size.height * scale).rounded())

        let format = UIGraphicsImageRendererFormat()
        format.scale = 1
        let renderer = UIGraphicsImageRenderer(size: target, format: format)
        let resized = renderer.image { _ in
            image.draw(in: CGRect(origin: .zero, size: target))
        }
        return resized.jpegData(compressionQuality: 0.8)
    }
}

private extension CGImagePropertyOrientation {
    init(_ orientation: UIImage.Orientation) {
        switch orientation {
        case .up: self = .up
        case .down: self = .down
        case .left: self = .left
        case .right: self = .right
        case .upMirrored: self = .upMirrored
        case .downMirrored: self = .downMirrored
        case .leftMirrored: self = .leftMirrored
        case .rightMirrored: self = .rightMirrored
        @unknown default: self = .up
        }
    }
}
